### ISSUE TITLE
Stub conditionals

### ISSUE THREAD

**Issue by dillingham** [stubkit/engine#39]
Not trying to create an entire language here.. 😂

But would be cool if there was some way of adding conditionals to stub files to determine whether or not to render blocks of content. 

```
{{stub:show_button}}
    <button>Add</button>
{{/stub}}
```
Where show_button is a variable in stub.json or evaluated after stub.php

I think else statements would probably be overkill and tricky
```
{{stub:show_button == false}}
    Else goes here
{{/stub}}
```

Probably lesser used but also:
```
{{stub:amount>5}}
```

**Comment by kitbs** [comment]
Good idea! Whenever I've tried to stub things in the past, I've reached for Blade/Twig so I could have some basic conditionals. But using Blade to stub a .blade.php file (Bladeception) was bonkers so I gave up!

I definitely see a need for a simple true/false conditional, like your first example. I'd say any other comparisons should be handled in a variable formatter etc.

I totally agree you should steer clear of anything more complicated like "else" blocks and inline expressions, until there was a clear use case. Otherwise you'll need get into lexer/parser territory... 😳

Can I suggest a syntax like {{stubif:variable}}...{{/stubif}} and then {{stubif!variable}}...{{/stubif}} for the "not"/"else" cases? They would be two separate blocks, rather than a three-part if/else/endif block.

Making sure you find the right closing tag is going to be the trick, especially if you have nested conditional blocks... Good luck! 😁
